version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Kind
          command: |
            curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.10.0/kind-$(uname)-amd64"
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
            kind -h
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            kubectl version --client
      - run:
          name: Create a cluster
          command: |
            kind create cluster --config cluster.yaml
      - run:
          name: Inspect the cluster
          command: |
            kubectl get nodes
